### ISSUE TITLE
I get the error   "  No such file or directory: 'models\\imagedataForKmeans.npy'  "

### ISSUE THREAD

**Issue by masouduut94** [mhyr/blader#1]
First of all, great project. Thanks for sharing.

After configuring all the dependencies for project I was unable to continue because of this error:

    File "/home/user/codes/blader/bibalabel/automatic.py", line 101, in reset
    myin = np.load('models\imagedataForKmeans.npy')
    File "/home/gpu/anaconda3/envs/msd_tur_seg/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
    FileNotFoundError: [Errno 2] No such file or directory: 'models\\imagedataForKmeans.npy'

Would you please guide me how to overcome this?

Also I wonder if running the `auto.py` is all I need to eventually be able to segment the wind turbines as you showed on thesis ? (Do I still need pretrained weights?)

Thanks Mahyar jan

**Comment by mhyr** [comment]
Hi Masoud,
The error stems from the fact that there is no feature space of a Resnet50 (imagedataForKmeans.npy) for the first run. Change the 7th parameter of the "autoPilot" function (namely kmeansReset)from False to True to build the feature space. 

About the segmentation, however, please note that this project does not aim to reach the best segmentation per se. The aim here is to reach the best balance between segmentation results and user intervention.

If you are specifically trying to reach good segmentation results with a clean and fast library. I would suggest taking a look at [U-net implementation at fast.ai](https://course.fast.ai/videos/?lesson=7).

**Comment by masouduut94** [comment]
Would you please check the email account you mentioned in readme file in this repo?
@mhyr
